### ISSUE TITLE
Using spf_max_paths along with desired_links or undesired_links can lead to no path found

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/pathfinder#37]
Hi,

Mef_eline requests `spf_max_paths=2` by default when ordering paths to pathfinder. However, with the recent introduction of CSPF integration in PR mef_eline/pull#198, if the user sends a request with desired and undesired links to Mef_eline then Pathfinder may return no path available depending on the topology.

Example:
1. Using Kytos-ng amlight/kytos docker with Mininet running the amlight topology
2. Submit a request to Path finder using the same attributes as mef_eline does:
```
# curl -s -X POST -H 'Content-type: application/json' http://127.0.0.1:8181/api/kytos/pathfinder/v2/ -d '{"source": "00:00:00:00:00:00:00:21:60", "destination":  "00:00:00:00:00:00:00:15:54", "spf_max_paths": 2, "undesired_links": ["3956ad11df6336618b11ba3da67c855f895310509d61d9f520b712e4b140320a"], "desired_links": ["5910658b867277df667e61954542fed34f0d65fdb6ebb1ac0c5baee3f0c0e953"]}' | jq -r
{
  "paths": []
}
```
3. Now, if we increase the spf_max_paths to 10:
```
# curl -s -X POST -H 'Content-type: application/json' http://127.0.0.1:8181/api/kytos/pathfinder/v2/ -d '{"source": "00:00:00:00:00:00:00:21:60", "destination":  "00:00:00:00:00:00:00:15:54", "spf_max_paths": 10, "undesired_links": ["3956ad11df6336618b11ba3da67c855f895310509d61d9f520b712e4b140320a"], "desired_links": ["5910658b867277df667e61954542fed34f0d65fdb6ebb1ac0c5baee3f0c0e953"]}' | jq -r '.paths[]|tostring'
{"cost":17,"hops":["00:00:00:00:00:00:00:21:60","00:00:00:00:00:00:00:21","00:00:00:00:00:00:00:21:14","00:00:00:00:00:00:00:18:14","00:00:00:00:00:00:00:18","00:00:00:00:00:00:00:18:11","00:00:00:00:00:00:00:11:11","00:00:00:00:00:00:00:11","00:00:00:00:00:00:00:11:9","00:00:00:00:00:00:00:17:9","00:00:00:00:00:00:00:17","00:00:00:00:00:00:00:17:10","00:00:00:00:00:00:00:12:10","00:00:00:00:00:00:00:12","00:00:00:00:00:00:00:12:4","00:00:00:00:00:00:00:15:4","00:00:00:00:00:00:00:15","00:00:00:00:00:00:00:15:54"]}
```

Since `spf_max_paths` don't seem to be a user provided parameter for CSPF (see below), we may need some adjustments in the way Pathfinder processes those attributes (maybe changing the order in which constraints are processed).

```
# grep spf_max_paths /src/kytos-mef-eline/ -R
/src/kytos-mef-eline/tests/unit/models/test_path.py:                    "spf_max_paths": max_paths,
/src/kytos-mef-eline/tests/unit/models/test_path.py:                    "spf_max_paths": max_paths,
/src/kytos-mef-eline/models/path.py:            "spf_max_paths": max_paths,
```

**Comment by viniarck** [comment]
@italovalcy, thanks for catching this. I've been doing some research about a solution and here's my take on this:


- You're right, we need to fix the order how the links constraints are processed. Any edges filtering should be done upfront before computing the shortest path as you've highlighted, which is how we're also doing when computing the constraints for metadata. That way "k" shortest_paths can be lazily and efficiently computed. `"undesired_links"` links can be filtered upfront on an edge bases, but `"desired_links"` links can't in the way same since any edge of a path can be included at some point, I'll expand on some implications about this below.
- Potential solutions to still fix `"desired_links"` would be **a)** to keep iterating on the k_shortest_paths until their exausted or when at least `spf_max_paths` are found, but the problem with this is that [Jin Y. Yen's algorithm -  a modified version of Dijkstra's](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.simple_paths.shortest_simple_paths.html#shortest-simple-paths) the worst time complexity is greater than O(KN**2), so depending on the number of nodes and edges this can easily take up to minutes (I'll give an example below) or even longer, which would be very problematic considering how locks are also being used. Another alternative **b)** would be to try to use an approach to try to polarize the shortest path to initially try include `"desired_links"` by offseting a value on the rest of any non desired link, this it's also not easy to deterministically polarize the paths, after all, the algorithm is greedy computed and it never knows upfront how many non desired links are also in the path and depending on the offset that might also not work, so that doesn't sound like a good option either and full of other edge cases.
- In retrospective, since when `"desired_links"` was first introduced, until we need to have to keep finding k shortest_paths (which is also vital for failover links), I think we should drop support for this feature, and whenever someone wants to polarize/guide a path selection can either try to think from a different angle and try to use `"undesired_links"` instead or use any of the other metadata links attributes like `"ownership"` and so on and so forth that they can also use to onstraint a path selection. 

Here's a script, computing 2 shortest simple paths in a `complete_graph(n)`, where it's trying to also simulate a case where an edge (1,3) as a desired_link that has one of the highest costs, where n will be exercised as 9, 8 and 3:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import networkx as nx


def compute_complete_graph(n) -> None:
    g = nx.complete_graph(n)
    print(g)
    for u, v in g.edges:
        g[u][v]["weight"] = 1
    edge = (1, 3)
    g[edge[0]][edge[1]]["weight"] = 1000
    max_paths = 2
    print("overwrote weights")

    found_paths = []
    print("Computing shortest paths...")
    for k, path in enumerate(nx.shortest_simple_paths(g, 0, 3, weight="weight")):
        if k % 1000 == 0:
            print(f"Iterated over {k} paths")
        for i in range(1, len(path)):
            if edge == (path[i - 1], path[i]):
                found_paths.append(path)
                print(f"Found path {path} during iteration {k}")
                break
        if len(found_paths) == max_paths:
            break
    print("Done")
    print(found_paths)


def main() -> None:
    """Main function."""
    compute_complete_graph(n=5)


if __name__ == "__main__":
    main()
```

- Execution with n=9, it took rouhgly 1 minute on my machine, notice that it computed over 11k paths to find at least two paths. Also 9 nodes and 36 edges could really be an actual real world network of a service provider:

```
❯ python complete_graph.py
Graph with 9 nodes and 36 edges
overwrote weights
Computing shortest paths...
Iterated over 0 paths
Iterated over 1000 paths
Iterated over 2000 paths
Iterated over 3000 paths
Iterated over 4000 paths
Iterated over 5000 paths
Iterated over 6000 paths
Iterated over 7000 paths
Iterated over 8000 paths
Iterated over 9000 paths
Iterated over 10000 paths
Iterated over 11000 paths
Found path [0, 1, 3] during iteration 11743
Found path [0, 2, 1, 3] during iteration 11744
Done
[[0, 1, 3], [0, 2, 1, 3]]

~/repos/pathfinder misc/auto_review*  1m 2s
```

- Execution with n=8, it took rouhgly 1.3 sec on my machine, not too bad, but it's still relatively high:


```
❯ time python complete_graph.py
Graph with 8 nodes and 28 edges
overwrote weights
Computing shortest paths...
Iterated over 0 paths
Iterated over 1000 paths
Found path [0, 1, 3] during iteration 1631
Found path [0, 2, 1, 3] during iteration 1632
Done
[[0, 1, 3], [0, 2, 1, 3]]
python complete_graph.py  1.29s user 0.03s system 99% cpu 1.325 total
```

- Execution with n=5 relatively decent, but this case the graph is relatively small:

```
❯ time python complete_graph.py
Graph with 5 nodes and 10 edges
overwrote weights
Computing shortest paths...
Iterated over 0 paths
Found path [0, 1, 3] during iteration 11
Found path [0, 2, 1, 3] during iteration 12
Done
[[0, 1, 3], [0, 2, 1, 3]]
python complete_graph.py  0.12s user 0.01s system 99% cpu 0.132 total
```



Could drop support for this `"desired_links"` links feature and bump `v3` API or if you have another suggestion? Let me know if you or anybody else sees another maintainable alternative.

**Comment by italovalcy** [comment]
Hi @viniarck , thanks for the detailed explanation and examples. It seems okay for me to drop support for desired_links for link. In fact, the undesired links seem to make much more sense in terms of use cases. The use cases I can think of for desired_links can also be mapped using the other constraints, such as ownership as you mentioned. Other than that, one could always request all paths with a higher spf_max_paths and then interact over the answer to choose those which includes the desired links.

Having said that, I support your proposal of dropping support for desired_links on the v3 API.
